### ISSUE TITLE
Example does not work in Rstudio

### ISSUE THREAD

**Issue by wligtenberg** [skranz/RTutor#12]
I am trying to get the Example problem set working in Rstudio.
When I use the check problemset addin, I get the following errors:

```
---------------------------
Save and check problem set file  ~/somelocation.Rmd  ...
Warning in readLines(ps$stud.file) :
  line 3 appears to contain an embedded nul
...
loads of those warnings
...
Warning in readLines(ps$stud.file) :
  line 369 appears to contain an embedded nul
Warning in readLines(ps$stud.file) :
  incomplete final line found on '/home/willem/git/training/sameness/sameness_training.rps'
Error in substring(txt, 1, nchar(pattern)): invalid multibyte string at '<ff>'
```

And it does not seem to work.

**Comment by skranz** [comment]
The "invalid multibyte string at '<ff>' suggests an encoding problem. Can you make sure that both your solution file (the Example_sol.Rmd) and the problem set file (the Example.Rmd file) are saved wit UTF-8 Encoding (in RStudio -> File -> Save with Encoding) and then don't have any funny characters?

If that does not help, you can email me the two files and I can check, whether I can replicate the problem on my computer. (Taking the examples from the RTutor page works on my computer)

**Comment by wligtenberg** [comment]
OK, I did that, although the default was utf-8 already.
And I reran everything again and now it works. So closing the issue.
