### ISSUE TITLE
Linux - RStudio installation problem 

### ISSUE THREAD

**Issue by kk-1** [skranz/RTutor#13]
Thanks for your efforts in making RTutor shared!

I am wondering if it is possible to use RTutor in Linux. Here is my experience:

I tried the solution on:
https://stackoverflow.com/questions/38345894/r-source-gist-not-working
the following get over the source_git problem :
devtools::source_gist("fad6062e5462c9d0efe4", filename = "install_rtutor.r")

But then (here is the R command I issued and the messages up to the first error):

Thanks in advance any way...
----------------------------------------------------------------------------------
install.rtutor(update.github=TRUE)

Install required packages from CRAN...Loading required package: whisker
Loading required package: stringr
Loading required package: jsonlite
Loading required package: data.table
data.table 1.10.4.2
  The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
  Documentation: ?data.table, example(data.table) and browseVignettes("data.table")
  Release notes, videos and slides: http://r-datatable.com
Loading required package: markdown
Loading required package: DT
Loading required package: dplyr

Attaching package: ‘dplyr’

The following objects are masked from ‘package:data.table’:

    between, first, last

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Loading required package: shiny

Attaching package: ‘shiny’

The following objects are masked from ‘package:DT’:

    dataTableOutput, renderDataTable

The following object is masked from ‘package:jsonlite’:

    validate

Loading required package: shinyBS
Loading required package: hwriter
trying URL 'https://cran.rstudio.com/src/contrib/hwriter_1.3.2.tar.gz'
Content type 'application/x-gzip' length 114012 bytes (111 KB)
==================================================
downloaded 111 KB

* installing *source* package ‘hwriter’ ...
** package ‘hwriter’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (hwriter)

The downloaded source packages are in
	‘/tmp/RtmpD9qGZg/downloaded_packages’
Loading required package: lmtest
Loading required package: zoo

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

Loading required package: texreg
trying URL 'https://cran.rstudio.com/src/contrib/texreg_1.36.23.tar.gz'
Content type 'application/x-gzip' length 494898 bytes (483 KB)
==================================================
downloaded 483 KB

* installing *source* package ‘texreg’ ...
** package ‘texreg’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (texreg)

The downloaded source packages are in
	‘/tmp/RtmpD9qGZg/downloaded_packages’
Loading required package: RCurl
Loading required package: bitops

Attaching package: ‘RCurl’

The following object is masked from ‘package:lmtest’:

    reset

Loading required package: memoise
Loading required package: shinyAce
trying URL 'https://cran.rstudio.com/src/contrib/shinyAce_0.2.1.tar.gz'
Content type 'application/x-gzip' length 1713619 bytes (1.6 MB)
==================================================
downloaded 1.6 MB

* installing *source* package ‘shinyAce’ ...
** package ‘shinyAce’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (shinyAce)

The downloaded source packages are in
	‘/tmp/RtmpD9qGZg/downloaded_packages’

Install required packages from Github...Downloading GitHub repo skranz/restorepoint@master
from URL https://api.github.com/repos/skranz/restorepoint/zipball/master
Installation failed: error in running command
Downloading GitHub repo skranz/stringtools@master
from URL https://api.github.com/repos/skranz/stringtools/zipball/master
Installation failed: error in running command
-------------------------------------------------------------------------------------------------

**Comment by skranz** [comment]
I just now tried installation on linux and it worked on my server. The gist basically just installs several packages. Installation from CRAN seems to work fine on your computer, but the errors arise when you want to install from Github.

Can you manually try to run
```
devtools::install_github("skranz/restorepoint")
devtools::install_github("skranz/stringtools")
```
If the same error arises, maybe try to install a new devtools version and try again.

Alternatively, I have now generated a Docker container that allows using RTutor via RStudio server:

https://hub.docker.com/r/skranz/rtutor/

If you already use Docker, that may now be the most convenient way to install and use RTutor.
