### ISSUE TITLE
Pre-run code chunks?

### ISSUE THREAD

**Issue by nolanpokpongkiat** [skranz/RTutor#17]
Hi,

I wanted to be able to have certain code chunks already executed when rendered to for example, show a plot or display a table. Is that currently supported, and if not, would it be possible to add that feature? Thanks so much.

**Comment by skranz** [comment]
Good suggestion. I added a new block type starting with the following line `#< preknit` and ending with a line `#>`.

All Rmd code inside a preknit block will be knitted and transformed to HTML at compile time and simple shown as HTML in the shiny version of the problem set. This is like an info block, but not put into a collapsible note. To show a plot just include a chunk in the preknit block that generates the plot. Note that all variables generated at earlier preknit or info blocks will be available at compile time at later preknit or info blocks.

Would this feature solve your issue?

To test it, you have to install the new RTutor version from Github, via
```r
devtools::install_github("skranz/RTutor", dep=FALSE)
```

**Comment by skranz** [comment]
Yes, it indeed makes sense to make the objects from extra.code.file available in the preknit blocks. I updated RTutor correspondingly (just install the new version from Github).

**Comment by nolanpokpongkiat** [comment]
Looks good, thanks!
