### ISSUE TITLE
Installation issue;

### ISSUE THREAD

**Issue by bernard-liew** [skranz/RTutor#18]
Hi,

I cannot seem to run the command in my console. It results in an error

```
if (!require(devtools)) 
  install.packages("devtools")

devtools::source_gist("gist.github.com/skranz/fad6062e5462c9d0efe4", filename="install_rtutor.r")
install.rtutor(update.github=TRUE)
library(RTutor)
```

Install required packages from CRAN...Loading required package: withr
Loading required package: whisker
Loading required package: stringr
Loading required package: jsonlite
Loading required package: data.table
data.table 1.12.2 using 4 threads (see ?getDTthreads).  Latest news: r-datatable.com
Loading required package: markdown
Loading required package: DT
Loading required package: dplyr

Attaching package: ‘dplyr’

The following objects are masked from ‘package:data.table’:

    between, first, last

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Loading required package: shiny

Attaching package: ‘shiny’

The following objects are masked from ‘package:DT’:

    dataTableOutput, renderDataTable

The following object is masked from ‘package:jsonlite’:

    validate

Loading required package: shinyBS
Loading required package: hwriter
Loading required package: lmtest
Loading required package: zoo

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

Loading required package: texreg
Version:  1.36.23
Date:     2017-03-03
Author:   Philip Leifeld (University of Glasgow)

Please cite the JSS article in your publications -- see citation("texreg").
Loading required package: RCurl
Loading required package: bitops

Attaching package: ‘RCurl’

The following object is masked from ‘package:lmtest’:

    reset

Loading required package: memoise
Loading required package: shinyAce
Loading required package: restorepoint

Install required packages from Github...Downloading GitHub repo skranz/stringtools@master
√  checking for file 'C:\Users\liew_\AppData\Local\Temp\Rtmp8QG1SH\remotesf60101c4ca5\skranz-stringtools-d03fb55/DESCRIPTION' ...
-  preparing 'stringtools':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'stringtools_0.01.tar.gz'
   
Installing package into ‘C:/Users/liew_/OneDrive/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'stringtools' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'stringtools'
    finding HTML links ... done
    adapt.blocks.after.replace              html  
    adapt.pos.after.replace                 html  
    blocks.add.level.0                      html  
    char.matrix.to.str                      html  
    char.vector.to.str                      html  
    check.str.par                           html  
    combine.pos.and                         html  
    combine.pos.list.and                    html  
    cumsum.ignore                           html  
    get.ignore                              html  
    has.substr                              html  
    ignore.and.complement.pos               html  
    ignore.to.pos                           html  
    merge.lines                             html  
    pos.complement                          html  
    pos.to.ignore                           html  
    pos.with.complement                     html  
    regexp.fixed                            html  
    replace.german.umlaute                  html  
    sep.lines                               html  
    str.at.pos                              html  
    str.between                             html  
    str.blocks.pos                          html  
    str.detect                              html  
    str.ends.with                           html  
    str.extract.all                         html  
    str.extract.first                       html  
    str.find                                html  
    str.inpos                               html  
    str.left                                html  
    str.left.of                             html  
    str.len                                 html  
    str.list.to.regexp.or                   html  
    str.locate.all                          html  
    str.locate.at.end                       html  
    str.locate.at.start                     html  
    str.locate.first                        html  
    str.matches.pattern                     html  
    str.number.matches                      html  
    str.remove.ends                         html  
    str.remove.ignore                       html  
    str.replace                             html  
    str.replace.at.pos                      html  
    str.replace.by.blocks                   html  
    str.replace.list                        html  
    str.right                               html  
    str.right.of                            html  
    str.space                               html  
    str.split                               html  
    str.split.at.pos                        html  
    str.starts.with                         html  
    str.tokenize                            html  
    str.trim                                html  
    to.char.matrix                          html  
    to.char.vector                          html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (stringtools)
Downloading GitHub repo skranz/shinyEvents@master
√  checking for file 'C:\Users\liew_\AppData\Local\Temp\Rtmp8QG1SH\remotesf6041bb4be4\skranz-shinyEvents-1d32196/DESCRIPTION' ...
-  preparing 'shinyEvents':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'shinyEvents_2.3.tar.gz'
   
Installing package into ‘C:/Users/liew_/OneDrive/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'shinyEvents' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'restorepoint' was built under R version 3.6.1
Execution halted
ERROR: lazy loading failed for package 'shinyEvents'
* removing 'C:/Users/liew_/OneDrive/Documents/R/win-library/3.6/shinyEvents'
Error : Failed to install 'shinyEvents' from GitHub:
  (converted from warning) installation of package ‘C:/Users/liew_/AppData/Local/Temp/Rtmp8QG1SH/filef6027f11e10/shinyEvents_2.3.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: package ‘whisker’ was built under R version 3.6.1 
2: package ‘markdown’ was built under R version 3.6.1 
3: package ‘dplyr’ was built under R version 3.6.1 
4: package ‘shinyBS’ was built under R version 3.6.1 
5: package ‘zoo’ was built under R version 3.6.1 
6: package ‘texreg’ was built under R version 3.6.1 
7: package ‘shinyAce’ was built under R version 3.6.1 
8: package ‘restorepoint’ was built under R version 3.6.1 
Downloading GitHub repo skranz/dplyrExtras@master
√  checking for file 'C:\Users\liew_\AppData\Local\Temp\Rtmp8QG1SH\remotesf6030a75c54\skranz-dplyrExtras-325491a/DESCRIPTION' ... 
-  preparing 'dplyrExtras':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'dplyrExtras_0.1.3.tar.gz'
   
Installing package into ‘C:/Users/liew_/OneDrive/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'dplyrExtras' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'dplyr' was built under R version 3.6.1
Execution halted
ERROR: lazy loading failed for package 'dplyrExtras'
* removing 'C:/Users/liew_/OneDrive/Documents/R/win-library/3.6/dplyrExtras'
Error : Failed to install 'dplyrExtras' from GitHub:
  (converted from warning) installation of package ‘C:/Users/liew_/AppData/Local/Temp/Rtmp8QG1SH/filef60eee781a/dplyrExtras_0.1.3.tar.gz’ had non-zero exit status
Downloading GitHub repo skranz/regtools@master
√  checking for file 'C:\Users\liew_\AppData\Local\Temp\Rtmp8QG1SH\remotesf6014bb462d\skranz-regtools-426fb24/DESCRIPTION' ... 
-  preparing 'regtools':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'regtools_2018.11.20.tar.gz'
   
Installing package into ‘C:/Users/liew_/OneDrive/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'regtools' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'restorepoint' was built under R version 3.6.1
Execution halted
ERROR: lazy loading failed for package 'regtools'
* removing 'C:/Users/liew_/OneDrive/Documents/R/win-library/3.6/regtools'
Error : Failed to install 'regtools' from GitHub:
  (converted from warning) installation of package ‘C:/Users/liew_/AppData/Local/Temp/Rtmp8QG1SH/filef601d647e7d/regtools_2018.11.20.tar.gz’ had non-zero exit status
Downloading GitHub repo skranz/RTutor@master
√  checking for file 'C:\Users\liew_\AppData\Local\Temp\Rtmp8QG1SH\remotesf6077b938af\skranz-RTutor-9ee4a5a/DESCRIPTION' ... 
-  preparing 'RTutor': (367ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'RTutor_2019.07.31.tar.gz'
   
Installing package into ‘C:/Users/liew_/OneDrive/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
ERROR: dependencies 'shinyEvents', 'dplyrExtras' are not available for package 'RTutor'
* removing 'C:/Users/liew_/OneDrive/Documents/R/win-library/3.6/RTutor'
Error : Failed to install 'RTutor' from GitHub:
  (converted from warning) installation of package ‘C:/Users/liew_/AppData/Local/Temp/Rtmp8QG1SH/filef6052154d78/RTutor_2019.07.31.tar.gz’ had non-zero exit status
 Show Traceback
 
 Rerun with Debug
 Error in library(RTutor) : there is no package called ‘RTutor’ *

Much appreciated for any help.
Bernard

**Comment by skranz** [comment]
Hi Bernard,

It looks like you have set `options(warn=2)` so that an error is thrown for every warning. I guess one can just ignore the warnings like
```
Error: (converted from warning) package 'restorepoint' was built under R version 3.6.1
```
Can you therefore try to first run
```r
options(warn=1)
```
and then install again?

You can also try to install then a single Github package as a test, e .g
```r
devtools::install_github("skranz/shinyEvents")
```

**Comment by bernard-liew** [comment]
Hi,

Thank you for responding. The code below ran fine.

`devtools::install_github("skranz/shinyEvents")`

But I still cannot install using:

`options (warn = 1)
if (!require(devtools)) 
  install.packages("devtools")

devtools::source_gist("gist.github.com/skranz/fad6062e5462c9d0efe4", filename="install_rtutor.r")
install.rtutor(update.github=TRUE)
library(RTutor)
`

Throws up the error for dplyrExtra and regtools, as belows

Installing package into ‘C:/Users/liew_/OneDrive/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'dplyrExtras' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'dplyr' was built under R version 3.6.1
Execution halted
ERROR: lazy loading failed for package 'dplyrExtras'
* removing 'C:/Users/liew_/OneDrive/Documents/R/win-library/3.6/dplyrExtras'
Error : Failed to install 'dplyrExtras' from GitHub:
  (converted from warning) installation of package ‘C:/Users/liew_/AppData/Local/Temp/Rtmp8QG1SH/filef6060da5264/dplyrExtras_0.1.3.tar.gz’ had non-zero exit status
Downloading GitHub repo skranz/regtools@master
√  checking for file 'C:\Users\liew_\AppData\Local\Temp\Rtmp8QG1SH\remotesf6066471e97\skranz-regtools-426fb24/DESCRIPTION' ...
-  preparing 'regtools':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'regtools_2018.11.20.tar.gz'
   
Installing package into ‘C:/Users/liew_/OneDrive/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'regtools' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'dplyr' was built under R version 3.6.1
Execution halted
ERROR: lazy loading failed for package 'regtools'
* removing 'C:/Users/liew_/OneDrive/Documents/R/win-library/3.6/regtools'
Error : Failed to install 'regtools' from GitHub:
  (converted from warning) installation of package ‘C:/Users/liew_/AppData/Local/Temp/Rtmp8QG1SH/filef60671e4dc1/regtools_2018.11.20.tar.gz’ had non-zero exit status
Downloading GitHub repo skranz/RTutor@master
√  checking for file 'C:\Users\liew_\AppData\Local\Temp\Rtmp8QG1SH\remotesf6046506f99\skranz-RTutor-9ee4a5a/DESCRIPTION' ...
-  preparing 'RTutor': (492ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'RTutor_2019.07.31.tar.gz'
   
Installing package into ‘C:/Users/liew_/OneDrive/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
ERROR: dependency 'dplyrExtras' is not available for package 'RTutor'
* removing 'C:/Users/liew_/OneDrive/Documents/R/win-library/3.6/RTutor'
Error : Failed to install 'RTutor' from GitHub:
  (converted from warning) installation of package ‘C:/Users/liew_/AppData/Local/Temp/Rtmp8QG1SH/filef60433413f0/RTutor_2019.07.31.tar.gz’ had non-zero exit status
 Show Traceback
 
 Rerun with Debug
 Error in library(RTutor) : there is no package called ‘RTutor’

**Comment by skranz** [comment]
Wow, I just realized that gmail put some of my Github notifications into the spam folder (is that Google's view on all emails from a Microsoft owned company?) Anyway, by luck I saw your reply...

That it does not work is strange. Your warnings are still converted to errors... maybe there is some strange new behavior in `install_github`... Can you try to install all problematic packages manually? Starting with:

```r
options(warn=1)
devtools::install_github("skranz/dplyrExtras")
```
and so on? Alternatively, if you don't want to host your own problem sets on shinyapps.io, you can also just try to install everything via

```r
options(warn=1)
install.packages("RTutor",repos = c("https://skranz-repo.github.io/drat/",getOption("repos")))
```

**Comment by bernard-liew** [comment]
Hi,

Many thanks again.

running
`
options(warn=1)
devtools::install_github("skranz/dplyrExtras")
`
Error: Failed to install 'dplyrExtras' from GitHub:

Running:
`options(warn=1)
install.packages("RTutor",repos = c("https://skranz-repo.github.io/drat/",getOption("repos")))`

is alright.

I do have another issue, in running the example code

`    library(RTutor)
    setwd(getwd())
    ps.name = "myps"; sol.file = paste0(ps.name,"_sol.Rmd")
    libs = c("ggplot2") # character vector of all packages you load in the problem set

    #name.rmd.chunks(sol.file)
    create.ps(sol.file=sol.file, ps.name=ps.name, libs=libs)
              
    # The following line directly shows the problem set 
    # in the browser
    show.ps(ps.name,launch.browser=TRUE,
      auto.save.code=FALSE,sample.solution=FALSE)`

Should I open another issue?

Bernard.

**Comment by skranz** [comment]
Sure you can open another issue. Above you did not write what the problem is.

**Comment by skranz** [comment]
Concerning the installation problem, I found now the problem. It is essentially similar to the one described here:

https://github.com/r-lib/remotes/issues/403

Mainly the package `remotes`, which `devtools:install_github` calls, automatically converts all warnings to errors unless one sets a specific environmental variable in R by calling:

```r
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
```

I now updated the gist by this call to avoid that warnings are converted to errors.
