### ISSUE TITLE
Window Position when clicking on "Go to next exercise..."

### ISSUE THREAD

**Issue by MartinKies** [skranz/RTutor#22]
When testing my problem sets I found that clicking on the "Go to next exercise..." button on RShiny brings me to the very top of the next exercise only when I test it with an uploaded shinyapps.io problemset and a never-before loaded exercise. 

If I test it locally OR when I go back to the previous exercise and click the button again in shinyapps.io my viewing window centers not at the very top but somewhere within the exercise - probably exactly the middle. 

This happens consistenly independent on the used Browser (tested: Chrome, Edge) and the problemset (tested: own, Clara Ulmer, FCollin). 

Is there a way to force the "Go to next exercise..." button to always go to the very top of the next exercise?

**Comment by skranz** [comment]
Thanks for the issue. That was always one of the points that I wanted to correct after having learned Shiny and Javascript a bit better, but never took the time. Until now. There is a new RTutor version on Github where the button should have the desired behavior. Could you take a look and test it on your computer?

**Comment by MartinKies** [comment]
Everything works now and the Exercise Button indeed brings me to the beginning of the very next exercise. Thank you very much!
