### ISSUE TITLE
Deletion of columns deletes more columns than expected

### ISSUE THREAD

**Issue by MartinKies** [skranz/RTutor#24]
Hello, its me again. I found pretty strange behavior regarding the deletion of columns of a data frame (and possibly a matrix, not tested). Please find a MWE attached. 

[MinDelExample_sol.zip](https://github.com/skranz/RTutor/files/4758757/MinDelExample_sol.zip)
![DeletionBehavior](https://user-images.githubusercontent.com/5664368/84273246-bc0c7600-ab2e-11ea-9118-b40fea99b7a3.png)

**Comment by MartinKies** [comment]
Yes you are right. Maybe something I will have a look at down the line. Right now I was able to circumvent the problem as per your suggestion. 

And you are right that just showing example_df[,-2] did indeed deliver the desired output. I confused myself there.

**Comment by skranz** [comment]
Just as a remark. Unrelated to the limitations of RTutor I also try to write my personal R code (at least the one outside packages) such that I can run a line twice without changing the result. E.g. if I want to remove a column, I like most to use a function like:

```r
remove.cols = function(dat, cols) {
  dat[,setdiff(colnames(dat), cols)]
}
```
which returns the same data frame even when called errorneously twice. (I don't like e.g. that `select(dat, -mycol)` would throw an error if `mycol` does not exist anymore in `dat`). The thing is that I most often work interactively with R and it often happens that I run only some but not all data preparation steps twice and it is nice if this does not yield by accident wrong results. In this sense, RTutor forces you to follow this convention.
