### ISSUE TITLE
New Options regarding rtutor.app.skel

### ISSUE THREAD

**Issue by MartinKies** [skranz/RTutor#25]
I added a lot of flexibility to the rTutor.app.skel Function in the LeverageData Fork as this suits our workflow. I am not sure which of those changes are in your interest, so I splittet them into different commits. In detail the new version is now possible to

1. Receive ps.show arguments and directly transfer them through. This allows to directly deploy an app which does not show solution buttons without having to go into global.R
2. Hide the "Download in RMarkdown" Button. I would much rather give my users directly the html file rather than having them build their own and receiving RMarkdown code.
3. Specify a different fork of RTutor - this allows us to use our GitHub Version for the shinyapps without having to manually change it in deployapps
4. Tell deployapps to have both safety if-clauses in deployapp off (i.e. set to TRUE). 
5. Set the shinyapps.io Account info directly. 

These in combinations allow us to have a single easily adaptable AppSkelett which directly generates the desired shinyapps and easily deploy them by sourcing deployapps.R without further modifications. This is quite helpful if one generates a lot of apps.

**Comment by MartinKies** [comment]
I forgot to add: All defaults are set in a way that exactly the same behavior happens as before if no options are set. Of course, all options have been documented in the helpfiles. I also tried to match your Programming Style to keep a uniform code.

**Comment by skranz** [comment]
Those changes sound great. Could you try to make a pull request so that I can add them to my RTutor branch? I have not yet much experience with pull requests, but hope the changes can be merged without conflict,

**Comment by MartinKies** [comment]
I have send a pull request :)

**Comment by skranz** [comment]
I merged the pull request without any merge conflict. Thanks a lot. Have not yet tested the new RTutor version though.
