### ISSUE TITLE
"Go to next exercise" Button does not trigger generation of code chunks

### ISSUE THREAD

**Issue by MartinKies** [skranz/RTutor#26]
There is a different behavior in the generation of code chunks when going through the tab at the top and the next exercise button. 

In particular the code chunks are not necessarily rendered at all. Please find attached a minimum working example where going through the tabs **does** generate the code chunk but ging through next exercise does not. 

[MWE_sol.zip](https://github.com/skranz/RTutor/files/4792129/MWE_sol.zip)

**Comment by skranz** [comment]
Thanks for the bug report. I uploaded a new RTutor version on Github that hopefully fixes the problem (and does so on my computer). Can you test it?

**Comment by MartinKies** [comment]
Yes everything works now as far as I have tested it - including the scrolling. Thank you very much!
