### ISSUE TITLE
Desired behavior of check.assign

### ISSUE THREAD

**Issue by MartinKies** [skranz/RTutor#28]
The default behavior of check.assign is ok.if.same.val = TRUE. The description states that FALSE is the default. I was quite confused why my expressions went through. Which is the desired behavior?

**Comment by skranz** [comment]
I initially set it to FALSE but then with some experience of RTutor problem sets in my courses I thought TRUE is the better default and changed it. Just forgot to update the documentation. I updated the documentation.
