### ISSUE TITLE
Width of Quizzes

### ISSUE THREAD

**Issue by MartinKies** [skranz/RTutor#29]
Hello :),

I have the curious behavior, that my quizzes do not use the available space (see Picture). 

I found nothing to control the width in the documentation nor in the source code of the package. In fact I am quite unsure why this happens, as I found nothing _limiting_ the width either - but I might have easily missed this. Do you have an idea how one can set the width of the quiz to the same width as the rest of the text?

Thank you in advance,
Martin
![Quiz small](https://user-images.githubusercontent.com/5664368/85946215-1a18c600-b943-11ea-8087-ed0f67799c5b.png)

**Comment by skranz** [comment]
The limited width seems to be the default CSS design used by the shiny package. However, you can change the CSS for wider quizzes as described [in issue 21](https://github.com/skranz/RTutor/issues/21).

**Comment by MartinKies** [comment]
Great! Yes that worked perfectly - thank you very much for the fast answer!
